# Generated by Django 5.0.1 on 2024-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('state', models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена')], default='start', max_length=20, verbose_name='Статус')),
                ('email_answer', models.BooleanField(default=False, verbose_name='Ответ от почты')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mailing', models.DateTimeField(blank=True, null=True, verbose_name='Время рассылки')),
                ('periodicity', models.CharField(choices=[('once_a_day', 'Раз в день'), ('once_a_week', 'Раз в неделю'), ('once_a_month', 'Раз в месяц')], default='once_a_day', verbose_name='Периодичность')),
                ('state', models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], default='start', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40, verbose_name='Тема письма')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
    ]
