# Generated by Django 5.0.1 on 2024-02-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mailing_periodicity_alter_mailing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Один раз в день', verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='state',
            field=models.CharField(choices=[('Запущена', 'Запущена'), ('Завершена', 'Завершена'), ('Создана', 'Создана')], default='Запущена', max_length=20, verbose_name='Статус'),
        ),
    ]
