# Generated by Django 5.0.1 on 2024-02-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_logs_mailing_mailing_message_mailing_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_activated',
            field=models.BooleanField(choices=[(True, 'Активна'), (False, 'Неактивна')], default=True, verbose_name='Активность'),
        ),
    ]
