# Generated by Django 5.0.1 on 2024-02-08 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_mailing_client_mailing_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('client_delete', 'Может удалять клиентов')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиентов'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'Лог сообщения', 'verbose_name_plural': 'Логов сообщений'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('start_date',), 'permissions': [('set_is_activated', 'Может отключать рассылку'), ('can_view', 'Может просматривать рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='logs',
            name='last_mailing_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='next_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующая рассылка'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало рассылки'),
        ),
    ]
