# Generated by Django 5.0.1 on 2024-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_mailing_time_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='state',
            field=models.CharField(blank=True, choices=[(True, 'Успешно'), (False, 'Неудача')], default=False, max_length=10, null=True, verbose_name='Попытка'),
        ),
    ]
