# Generated by Django 5.0.1 on 2024-02-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_logs_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='client',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='main.client', verbose_name='клиент'),
        ),
    ]
